### ISSUE TITLE
BARA PLEASE FIX THE DEMO

### ISSUE THREAD

**Issue by peanut-weanut** [itsnsix/7dfps2024#23]
Cursor locking, tuning the controller

**Comment by Wilbe-coding** [comment]
very good sire needful will be done 🇮‍🇳

**Comment by Wilbe-coding** [comment]
if event is InputEvent:
		Input.mouse_mode = Input.MOUSE_MODE_CAPTURED

**Comment by Wilbe-coding** [comment]
Commit 5723568
